# Generated by Django 5.2.11 on 2026-02-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Electronics', 'ELECTRONICS'), ('Clothing', 'CLOTHING'), ('Sports', 'SPORTS'), ('Furniture', 'FURNITURE'), ('Books', 'BOOKS')], max_length=20)),
                ('price', models.FloatField(max_length=10)),
                ('stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
