# Generated by Django 5.2.11 on 2026-02-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'ELECTRONICS'), ('clouthing', 'CLOUTHING'), ('sport', 'SPORTS'), ('furniture', 'FURNITURE'), ('books', 'BOOKS')], max_length=20),
        ),
    ]
