# Generated by Django 5.2.11 on 2026-02-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodc', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'ELECTRONICS'), ('clothing', 'CLOTHING'), ('sports', 'SPORTS'), ('furniture', 'FURNITURE'), ('books', 'BOOKS')], max_length=20),
        ),
    ]
