# Generated by Django 5.2.11 on 2026-02-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodc', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
