# Generated by Django 5.2.11 on 2026-02-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodc', '0004_alter_product_price_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'ELECTRONICS'), ('Clothing', 'CLOTHING'), ('Sports', 'SPORTS'), ('Furniture', 'FURNITURE'), ('Books', 'BOOKS')], max_length=20),
        ),
    ]
